# Generated by Django 3.1 on 2020-08-12 11:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('tag_full_name', models.CharField(default='Fullname is none', max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='Public date')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('non_utf8_title', models.CharField(default='This is title a Article', max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Public date')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('view', models.IntegerField(default=0)),
                ('last_modify', models.DateTimeField(null=True)),
                ('tags', models.ManyToManyField(to='theblog.Tag')),
            ],
        ),
    ]
