# Generated by Django 3.1 on 2020-08-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='non_utf8_title',
        ),
    ]
