# Generated by Django 3.1 on 2020-08-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_remove_article_non_utf8_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='this-is-slug', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_modify',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
