# Generated by Django 3.1 on 2020-08-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_auto_20200812_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
