# Generated by Django 3.1 on 2020-08-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_tag_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to='thumbs'),
        ),
    ]
