# Generated by Django 3.1 on 2020-08-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_article_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbs'),
        ),
    ]
