# Generated by Django 3.1 on 2020-08-25 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
